### PR TITLE
Corrects hundreds of dark mode related bugs. Also corrects the missin…

### PR DESCRIPTION
**Pull request by kirvanp**
…g "Done" buttons in the iPhone layout. Updates the target to iOS 13.4 and corrects all of the associated warnings except those related to the rarely used bluetooth features

### CODE REVIEW

**Comment by LukeTowers** [comment]
@kirvanp you might have to pull this repo's master branch back into yours to resolve the merge conflicts.

**Comment by kirvanp** [comment]
> @kirvanp you might have to pull this repo's master branch back into yours to resolve the merge conflicts.

Are there still merge conflicts? It popped up with about half a dozen which I manually resolved so it seemed ok.

**Comment by LukeTowers** [comment]
Screen Shot 2021-04-29 at 9 48 29 AM
Looks like it, see above. There could have been merge conflicts between your branches, or there could have been the same merge conflicts when you merge this repo's master branch into yours, but as far as I can tell the resolved conflicts haven't been pushed back up to your branch yet to show up in the PR. See the image below that demonstrates the misalignment between the branches:

Screen Shot 2021-04-29 at 9 50 15 AM

**Comment by kirvanp** [comment]
Ok how about now?

**Comment by LukeTowers** [comment]
@kirvanp looks good now!

**Comment by huguesfcadets** [comment]
Missing changes from the master branch. Update your local repository, correct any compile error, then commit and push. The pull request should update with correct version of files.

The issue is with that method call `addOrRemoveDoneButtonGivenTraitCollection`.

A good practice is to update from origin often. From GitHub.com, in your forked repository, click **Fetch upstream**, and **Fetch and Merge**. Then from your local repo, do a pull. (any better way to do that??)

**Comment by LukeTowers** [comment]
@huguesfcadets you can setup upstream as a separate remote (I usually just call it "upstream") and then merge directly from that remote into your local copy. That's what I do typically.

**Comment by huguesfcadets** [comment]
@LukeTowers , are you saying on the pr branch? Which require the fork owner to give me permission. Otherwise, you are suggesting that I merge the pr into a local copy, then push back to the master... I'm confused. Thanks to clarify.

**Comment by LukeTowers** [comment]
@huguesfcadets I was suggesting an easier way of keeping downstream repos up to date more easily in reference to your comment about how you recommend doing it at the moment:

> A good practice is to update from origin often. From GitHub.com, in your forked repository, click Fetch upstream, and Fetch and Merge. Then from your local repo, do a pull. (any better way to do that??)

My suggestion would be applicable to @kirvanp, you couldn't do those steps for him unless you have push access to his repository.

**Comment by huguesfcadets** [comment]
Changes have been integrated into the main branch through pull request #68

**Pull request closed without merging**
